// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Official Robinhood stock tokens on Robinhood Chain mainnet, joined with
// their Chainlink price-feed proxies. Regenerate when Robinhood lists new
// tokens: node scripts/gen-registry.mjs

export interface StockEntry {
  ticker: string;
  /** Company name, e.g. "NVIDIA" */
  name: string;
  /** Official stock-token contract (ERC-20, 18 decimals) */
  token: `0x${string}`;
  /** Chainlink AggregatorV3 proxy for TICKER/USD (8 decimals) */
  feed: `0x${string}`;
  /** Robinhood CDN icon, if any */
  icon: string | null;
}

export const STOCKS: StockEntry[] = [
  { ticker: "NVDA", name: "NVIDIA", token: "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC", feed: "0x379EC4f7C378F34a1B47E4F3cbeBCbAC3E8E9F15", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xd0601ce157db5bdc3162bbac2a2c8af5320d9eec.png" },
  { ticker: "AAPL", name: "Apple", token: "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9", feed: "0x6B22A786bAa607d76728168703a39Ea9C99f2cD0", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xaf3d76f1834a1d425780943c99ea8a608f8a93f9.png" },
  { ticker: "SPCX", name: "Space Exploration Technologies Corp", token: "0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa", feed: "0xB265810950ba6c5C0Ff821c9963014a56fD8Bffb", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x4a0e65a3eccec6dbe60ae065f2e7bb85fae35eea.png" },
  { ticker: "GOOGL", name: "Alphabet Class A", token: "0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3", feed: "0xF6f373a037c30F0e5010d854385cA89185AE638b", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x2e0847e8910a9732eb3fb1bb4b70a580adad4fe3.png" },
  { ticker: "TSLA", name: "Tesla", token: "0x322F0929c4625eD5bAd873c95208D54E1c003b2d", feed: "0x4A1166a659A55625345e9515b32adECea5547C38", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x322f0929c4625ed5bad873c95208d54e1c003b2d.png" },
  { ticker: "AMZN", name: "Amazon", token: "0x12f190a9F9d7D37a250758b26824B97CE941bF54", feed: "0xD5a1508ceD74c084eBf3cBe853e2C968fB2a651C", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x12f190a9f9d7d37a250758b26824b97ce941bf54.png" },
  { ticker: "AMD", name: "AMD", token: "0x86923f96303D656E4aa86D9d42D1e57ad2023fdC", feed: "0x943A29E7ae51A4798823ca9eEd2ed533B2A22C72", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x86923f96303d656e4aa86d9d42d1e57ad2023fdc.png" },
  { ticker: "PLTR", name: "Palantir Technologies", token: "0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A", feed: "0x820ABedFF239034956B7A9d2F0a331f9F075eB4c", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x894e1ec2d74ffe5aef8dc8a9e84686accb964f2a.png" },
  { ticker: "MSFT", name: "Microsoft", token: "0xe93237C50D904957Cf27E7B1133b510C669c2e74", feed: "0x45C3C877C15E6BA2EBB19eA114Ea508d14C1Af2E", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xe93237c50d904957cf27e7b1133b510c669c2e74.png" },
  { ticker: "META", name: "Meta Platforms", token: "0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35", feed: "0x7C38C00C30BEe9378381E7B6135d7283356D71b1", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xc0d6457c16cc70d6790dd43521c899c87ce02f35.png" },
  { ticker: "ORCL", name: "Oracle", token: "0xb0992820E760d836549ba69BC7598b4af75dEE03", feed: "0x0e6a64a2B58A6693a531E6c555f3A5d042eEA844", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xb0992820e760d836549ba69bc7598b4af75dee03.png" },
  { ticker: "COIN", name: "Coinbase", token: "0x6330D8C3178a418788dF01a47479c0ce7CCF450b", feed: "0xA3a468A452940B7D6b69991207B508c609a98Ef2", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x6330d8c3178a418788df01a47479c0ce7ccf450b.png" },
  { ticker: "MU", name: "Micron Technology", token: "0xfF080c8ce2E5feadaCa0Da81314Ae59D232d4afD", feed: "0x425EEFdCf05ed6526C3cE61Af99429A228a6d596", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xff080c8ce2e5feadaca0da81314ae59d232d4afd.png" },
  { ticker: "INTC", name: "Intel", token: "0xc72b96e0E48ecd4DC75E1e45396e26300BC39681", feed: "0x3f390C5C24628Ac7C489515402235FeAD71D1913", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xc72b96e0e48ecd4dc75e1e45396e26300bc39681.png" },
  { ticker: "CRWV", name: "CoreWeave", token: "0x5f10A1C971B69e47e059e1dC91901B59b3fB49C3", feed: "0xe1b3aABCAFAd1c94708dc1367dcfF8Aa4407487C", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x5f10a1c971b69e47e059e1dc91901b59b3fb49c3.png" },
  { ticker: "USAR", name: "USA Rare Earth", token: "0xd917B029C761D264c6A312BBbcDA868658eF86a6", feed: "0xA994d3684e8400A6c8078226925779FdeE682DD9", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xd917b029c761d264c6a312bbbcda868658ef86a6.png" },
  { ticker: "SNDK", name: "Sandisk Corporation", token: "0xB90A19fF0Af67f7779afF50A882A9CfF42446400", feed: "0xfb133Fa4B7b385802B693a293606682Df47109A3", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xb90a19ff0af67f7779aff50a882a9cff42446400.png" },
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", token: "0x117cc2133c37B721F49dE2A7a74833232B3B4C0C", feed: "0x319724394D3A0e3669269846abE664Cd621f9f6A", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x117cc2133c37b721f49de2a7a74833232b3b4c0c.png" },
  { ticker: "QQQ", name: "Invesco QQQ", token: "0xD5f3879160bc7c32ebb4dC785F8a4F505888de68", feed: "0x80901d846d5D7B030F26B480776EE3b29374C2ae", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xd5f3879160bc7c32ebb4dc785f8a4f505888de68.png" },
  { ticker: "USO", name: "United States Oil Fund", token: "0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344", feed: "0x75a9c76Ef439e2C7c2E5a34Ab105EcFe3766431c", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xa30fa36db767ad9ed3f7a60fc79526fb4d56d344.png" },
  { ticker: "CRCL", name: "Circle Internet Group", token: "0xdF0992E440dD0be65BD8439b609d6D4366bf1CB5", feed: "0x6652eDf64bA3731C4F2D3ce821A0Fb1f1f6b482a", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xdf0992e440dd0be65bd8439b609d6d4366bf1cb5.png" },
  { ticker: "SLV", name: "iShares Silver Trust", token: "0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f", feed: "0x209b73908e92Ae021826eD79609845451Ecba2ce", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x411efb0e7f985935daec3d4c3ebaea0d0ad7d89f.png" },
  { ticker: "SGOV", name: "iShares 0-3 Month Treasury Bond ETF", token: "0x92FD66527192E3e61d4DDd13322Aa222DE86F9B5", feed: "0xa0DF4ee0fFf975306345875E3548Fcc519577A11", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x92fd66527192e3e61d4ddd13322aa222de86f9b5.png" },
  { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", token: "0x58FfE4a942d3885bAa22D7520691F611EF09e7AA", feed: "0x874cF94aa8eC88Fd9560094dD065f2fB3E41Fc2F", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x58ffe4a942d3885baa22d7520691f611ef09e7aa.png" },
  { ticker: "GME", name: "GameStop", token: "0x1b0E319c6A659F002271B69dB8A7df2F911c153E", feed: "0x27C71df6A64fB476468EdF256CF72c038baB5B67", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x1b0e319c6a659f002271b69db8a7df2f911c153e.png" },
  { ticker: "BABA", name: "Alibaba", token: "0xad25Ac6C84D497db898fa1E8387bf6Af3532a1c4", feed: "0x62Cc8F9b5f56a33c9C8A60c8B92779f523c4E984", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xad25ac6c84d497db898fa1e8387bf6af3532a1c4.png" },
  { ticker: "NBIS", name: "Nebius Group", token: "0x9D9c6684F596F66a64C030B93A886D51Fd4D7931", feed: "0xE1D87B116Ba0fe898998f1D140339D1fA1E09705", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x9d9c6684f596f66a64c030b93a886d51fd4d7931.png" },
  { ticker: "MSTR", name: "Strategy Inc.", token: "0xec262a75e413fAfD0dF80480274532C79D42da09", feed: "0x396118bdFB181e6240E74D243F266B061c0edc3D", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xec262a75e413fafd0df80480274532c79d42da09.png" },
  { ticker: "RKLB", name: "Rocket Lab Corporation", token: "0x3b14C39E89D60D627b42a1A4CA45b5bb45Fc12e2", feed: "0x045477BF65Aef6f4F2386ad0164579e48381CC74", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x3b14c39e89d60d627b42a1a4ca45b5bb45fc12e2.png" },
  { ticker: "ASML", name: "ASML Holding NV", token: "0x47F93d52cBeC7C6D2CfC080e154002370a60dAEA", feed: "0xB4106147E8cce40b7d46124090d373A71b70f87D", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x47f93d52cbec7c6d2cfc080e154002370a60daea.png" },
  { ticker: "IONQ", name: "IonQ", token: "0x558378E000D634A36593E338eBacdd6207640EfE", feed: "0x22EfeC4919baf55F360E0EDee4AbEB26DE4971eb", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x558378e000d634a36593e338ebacdd6207640efe.png" },
  { ticker: "EWY", name: "iShares MSCI South Korea fund", token: "0x7f0aBeF0C07280F82c6a08ead09dEd6BAE2C13Fc", feed: "0xEFdf54610B62A7753Ec30bDc380847c12D32e1D1", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x7f0abef0c07280f82c6a08ead09ded6bae2c13fc.png" },
  { ticker: "RGTI", name: "Rigetti Computing", token: "0x284358abc07F9359f19f4b5b4aC91901Be2597Ba", feed: "0x2A045cF1C49c61c166C036d2f06FA2D2d984f765", icon: "https://cdn.robinhood.com/ncw_assets/logos/0x284358abc07f9359f19f4b5b4ac91901be2597ba.png" },
  { ticker: "CLSK", name: "CleanSpark", token: "0xcBB95BBF36099d34dA091dc6Fa6F49EfA257Cee3", feed: "0x810c12D3a554Bc47fd39597Fe3b3AAC4941F50eF", icon: "https://cdn.robinhood.com/ncw_assets/logos/0xcbb95bbf36099d34da091dc6fa6f49efa257cee3.png" },
];

export const STOCK_BY_TICKER = new Map(STOCKS.map((s) => [s.ticker, s]));
